version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.2
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.2.4
    NOCOMPAT: true
  - LUA_VER: 5.3.1
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

init:
# Setup Lua development/build environment
# Make VS 2013 command line tools available
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks make rockspecs/bitness-scm-0.rockspec

before_test:
# install test only deps

test_script:
- echo "Testing..."
- lua "%APPVEYOR_BUILD_FOLDER%\test\test.lua"

after_test:
